-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;

DROP TABLE IF EXISTS public.fact_order;

DROP TABLE IF EXISTS public.dim_item;
CREATE TABLE IF NOT EXISTS public.dim_item
(
    item_id integer NOT NULL,
    item_name character varying(32) COLLATE pg_catalog."default",
    item_ppu numeric,
    CONSTRAINT dim_item_pkey PRIMARY KEY (item_id)
);

DROP TABLE IF EXISTS public.dim_location;
CREATE TABLE IF NOT EXISTS public.dim_location
(
    location_type_id integer NOT NULL,
    location_type character varying(32) COLLATE pg_catalog."default",
    CONSTRAINT dim_location_pkey PRIMARY KEY (location_type_id)
);

DROP TABLE IF EXISTS public.dim_payment;
CREATE TABLE IF NOT EXISTS public.dim_payment
(
    payment_type_id integer NOT NULL,
    payment_type character varying(32) COLLATE pg_catalog."default",
    CONSTRAINT dim_payment_pkey PRIMARY KEY (payment_type_id)
);

CREATE TABLE IF NOT EXISTS public.fact_order
(
    transaction_id character(11) COLLATE pg_catalog."default" NOT NULL,
    item_id integer,
    item_quantity integer,
    item_total_price numeric,
    payment_type_id integer,
    location_type_id integer,
    transaction_date date,
    CONSTRAINT fact_order_pkey PRIMARY KEY (transaction_id)
);

ALTER TABLE IF EXISTS public.fact_order
    ADD CONSTRAINT fact_order_item_id_fkey FOREIGN KEY (item_id)
    REFERENCES public.dim_item (item_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_order
    ADD CONSTRAINT fact_order_location_type_id_fkey FOREIGN KEY (location_type_id)
    REFERENCES public.dim_location (location_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;


ALTER TABLE IF EXISTS public.fact_order
    ADD CONSTRAINT fact_order_payment_type_id_fkey FOREIGN KEY (payment_type_id)
    REFERENCES public.dim_payment (payment_type_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION;

END;